### ISSUE TITLE
collectory stops working after some hours with a mysql ComunicationsException

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/collectory-plugin#190]
Using `ala-collectory` `1.6.6` (`collectory` `1.9.11.`), in `u18.04,` collections stop to work after some hours and did not auto recover. The logs: 

```
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <plugin:isAvailable>: Error executing tag <ala:systemMessage>: Could not commit Hibernate transaction;nested exception is org.hibernate.TransactionException: JDBC commit failed
        at gsp_alaCollectory_layoutsala_gsp$_run_closure1$_closure3.doCall(gsp_alaCollectory_layoutsala_gsp.groovy:63)
        at gsp_alaCollectory_layoutsala_gsp$_run_closure1.doCall(gsp_alaCollectory_layoutsala_gsp.groovy:70)
        ... 14 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <ala:systemMessage>: Could not commit Hibernate transaction; nested exception is org.hibernate.TransactionException: JDBC commit failed
        at gsp_alaCollectory_layoutsala_gsp$_run_closure1$_closure3$_closure7.doCall(gsp_alaCollectory_layoutsala_gsp.groovy:60)
        ... 16 more
Caused by: org.springframework.transaction.TransactionSystemException: Could not commit Hibernate transaction; nested exception is org.hibernate.TransactionException: JDBC commit failed
        at au.org.ala.admin.SystemMessageTagLib.showSystemMessage(SystemMessageTagLib.groovy:16)
        at au.org.ala.admin.SystemMessageTagLib$_closure1.doCall(SystemMessageTagLib.groovy:12)
        ... 17 more
Caused by: org.hibernate.TransactionException: JDBC commit failed
        ... 19 more
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 88,044,455 milliseconds ago. The last packet sent successfully to the server was 88,044,455 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
        at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:811)
        ... 19 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 88,044,455 milliseconds ago. The last packet sent successfully to the server was 88,044,455 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasingthe server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
```

it needs a manual restart to recover the service.

As a temporary workaround  I rolled back the mysql connector and now is stable:
```
     dependencies {
-        runtime 'mysql:mysql-connector-java:8.0.25'
+        runtime 'mysql:mysql-connector-java:5.1.42'
```

What I see among other things is that [ValidationQuery is empty]( 
https://github.com/AtlasOfLivingAustralia/collectory-plugin/blob/2ed9737c04db9a07fe9052d40ece43c4e5a2b207/grails-app/conf/DataSource.groovy#L68) while in other modules [is configured](https://github.com/AtlasOfLivingAustralia/ala-cas-5/blob/a1007570e71fb14ad46e1a1134790ec710fbfec6/etc/cas/config/application.yml#L125). So some of this jdbc [data source params](https://docs.grails.org/latest/guide/conf.html#dataSource) should we configured better. 

Maybe this `collectory` instability was mentioned  previously [here](https://github.com/AtlasOfLivingAustralia/data-management/issues/779).

**Comment by meshackjr** [comment]
Facing the same issue with collectory 1.6.6
