### ISSUE TITLE
Error when ProviderMap does not have a collection

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/collectory-plugin#72]
ProviderMap looks like it should work without a collection, if the "matchAnyCollectionCode" option is set to true. However, it fails with a jdbc exception about a failed non-null constraint when actually attempting to save a provider map that has no collections mapped to it.

Stacktrace is as follows, noting that Grails/Hibernate/etc. are rewriting the code so the stacktrace doesn't actually match the sourcecode from ProviderMapController or ProviderMap:

```
2016-05-16 01:13:16,871 ERROR [JDBCExceptionReporter] Column 'collection_id' cannot be null
2016-05-16 01:13:17,003 ERROR [GrailsExceptionResolver] MySQLIntegrityConstraintViolationException occurred when processing request: [POST] /providerMap/save
Column 'collection_id' cannot be null. Stacktrace follows:
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'collection_id' cannot be null
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1016)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3376)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3308)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1837)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1961)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2543)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1737)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2022)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1940)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1925)
	at au.org.ala.collectory.ProviderMapController$_closure4.doCall(ProviderMapController.groovy:63)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:196)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:189)
	at au.org.ala.cas.client.AlaHttpServletRequestWrapperFilter.doFilter(AlaHttpServletRequestWrapperFilter.java:66)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:189)
	at org.jasig.cas.client.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:93)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:189)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ansell** [comment]
Manually changing collection_id to be nullable works, but not sure how to make it work by default with the way the database is generated from code.

In particular, the steps I went through to change the database are:

    DROP INDEX `collection_id` ON `collectory`.`provider_map`

    ALTER TABLE `collectory`.`provider_map` 
    
    CHANGE COLUMN `collection_id` `collection_id` BIGINT(20) NULL ;

    CREATE INDEX `idx_provider_map_collection_id`  ON `collectory`.`provider_map` (collection_id) COMMENT '' ALGORITHM DEFAULT LOCK DEFAULT

After that, provider maps can be added that have a non-null institution_id and a null collection_id.

Not sure what will happen with biocache-store after that, but will explore that once this issue is fixed.

**Comment by ansell** [comment]
For my reference in the future, the command I used to tunnel into the vagrant box used to run the mysql commands from a local instance of MySQL Workbench was:

    ssh -L 3306:localhost:3306 -i ~/.vagrant.d/insecure_private_key vagrant@10.1.1.3
