### ISSUE TITLE
OutOfMemoryError when attempting to download a file

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/collectory-plugin#84]
I am unable to download a particular file from the collectory due to an OutOfMemoryError. The request results in an HTTP 500 response (which may be generated or mapped by a proxy server operated by IM&T that sits in front of the collectory. It isn't clear why the size of the file should necessarily affect requests unless they are being copied into main memory accidentally.

The stacktrace is:
```
2016-11-28 12:03:49,863 ERROR [GrailsExceptionResolver] OutOfMemoryError occurred when processing request: [GET] /upload/1480294739317/Mapped-Archive-MBarkla-20160725-plus-20160608.zip
Java heap space. Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [fileDownload] of controller [au.org.ala.collectory.DataController] in plugin [collectory] caused exception: Runtime error executing action
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	... 10 more
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by ansell** [comment]
It appears as though the file is indeed being copied into main memory, but I am not a groovy expert so I may have misinterpreted the following line:

https://github.com/AtlasOfLivingAustralia/collectory-plugin/blob/master/grails-app/controllers/au/org/ala/collectory/DataController.groovy#L291
```groovy
 response.outputStream << file.bytes
```

**Comment by djtfmartin** [comment]
See #75
